version: "3.9"

services:
  notification-api:
    build: .
    container_name: notification-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8010:8000"
    env_file: .env
    depends_on:
      - notification-db
      - notification-redis
    volumes:
      - .:/app

  notification-worker:
    build: .
    container_name: notification-worker
    command: celery -A app.workers.celery_app worker --loglevel=info -Q dispatch,retry,dlq
    env_file: .env
    depends_on:
      - notification-db
      - notification-redis

  notification-beat:
    build: .
    container_name: notification-beat
    command: celery -A app.workers.celery_app beat --loglevel=info
    env_file: .env
    depends_on:
      - notification-redis

  notification-db:
    image: postgres:16-alpine
    container_name: notification-db
    environment:
      POSTGRES_USER: notify
      POSTGRES_PASSWORD: notify
      POSTGRES_DB: notification_service
    ports:
      - "5433:5432"
    volumes:
      - notification_pgdata:/var/lib/postgresql/data

  notification-redis:
    image: redis:7-alpine
    container_name: notification-redis
    ports:
      - "6380:6379"

volumes:
  notification_pgdata:
